# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

before_cache: Rscript -e 'install.packages("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(tarball = ".")'
  skip_cleanup: true
