on:
  push:
    branches: master

name: trigger-scmerge-docker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SCMERGE_DOCKER_TOKEN }}
          event-type: my-event
